ci:
  autofix_prs: false
  autoupdate_branch: dev
  autoupdate_schedule: monthly
  skip: [ty]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        exclude: "^(kwja/resource/.*|uv\\.lock)$"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.65
    hooks:
      - id: ty
  -   repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.11.0.1
      hooks:
        - id: shellcheck
          files: ^scripts/
          types: [ shell ]
          args: [ --exclude=SC2002 ]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
