defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, typo_module_writer, progress_bar]
  - datamodule: typo
  - dataset: typo
  - logger: wandb
  - encoder: char_roberta_large
  - module: typo
  - optimizer: adamw
  - scheduler: constant_schedule_with_warmup
  - trainer: default
  - _self_

max_seq_length: 512
do_predict_after_train: true
checkpoint_path: ""

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/loss
mode: min
# option
confidence_threshold: 0.9   # valid only for inference

# hyper-parameters to be tuned
warmup_steps: 100
effective_batch_size: 16

# environment dependent settings
devices: ${oc.env:GPUS,0}
max_batches_per_device: 2
num_workers: 0

ignore_hparams_on_save: false
hparams_to_ignore_on_save:
  - project
  - work_dir
  - seed
  - name
  - exp_dir
  - run_id
  - run_dir
  - config_name
  - callbacks:
    - early_stopping
    - model_checkpoint
    - model_summary
    - progress_bar
  - datamodule:
    - train
    - valid
    - test
  - logger
  - hparams_to_ignore_on_save
