import torch

from jula.evaluators.phrase_analysis_metric import PhraseAnalysisMetric
from jula.utils.constants import BASE_PHRASE_FEATURES, IGNORE_INDEX

"""  Example
# S-ID:0-1
* 0
+ 0 <体言>
お腹 <基本句-主辞>
が <基本句-区切><文節-区切>
* 1
+ 1 <用言:動><時制:過去><節-区切><節-主辞><レベル:B+><動態述語><節-機能-原因・理由:ので>
空いた <基本句-主辞><用言表記先頭><用言表記末尾>
ので <基本句-区切><文節-区切>
* 2
+ 2 <体言>
ご飯 <基本句-主辞>
を <基本句-区切><文節-区切>
* 3
+ 3 <用言:動><モダリティ-意志><モダリティ-勧誘><節-区切><節-主辞><レベル:C><敬語:丁寧表現>
食べ <基本句-主辞><用言表記先頭><用言表記末尾>
ましょう
。 <基本句-区切><文節-区切>
EOS
"""

word_feature_predictions = torch.tensor(
    [
        [
            [1, 0, 0, 0, 0],  # お腹
            [0, 1, 1, 0, 0],  # が
            [1, 0, 0, 1, 1],  # 空いた
            [0, 1, 1, 0, 0],  # ので
            [1, 0, 0, 0, 0],  # ご飯
            [0, 1, 1, 0, 0],  # を
            [1, 0, 0, 1, 0],  # 食べ (<用言表記末尾>ではないと間違って予測)
            [0, 1, 0, 0, 1],  # ましょう (<基本句-区切>、<用言表記末尾>だと間違って予測)
            [0, 1, 1, 0, 0],  # 。
        ]
    ],
    dtype=torch.long,
)
word_features = torch.tensor(
    [
        [
            [1, 0, 0, 0, 0],  # お腹
            [0, 1, 1, 0, 0],  # が
            [1, 0, 0, 1, 1],  # 空いた
            [0, 1, 1, 0, 0],  # ので
            [1, 0, 0, 0, 0],  # ご飯
            [0, 1, 1, 0, 0],  # を
            [1, 0, 0, 1, 1],  # 食べ
            [0, 0, 0, 0, 0],  # ましょう
            [0, 1, 1, 0, 0],  # 。
        ]
    ],
    dtype=torch.long,
)

base_phrase_feature_predictions = torch.tensor(
    [
        [
            # お腹
            [
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # が
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # 空いた (<用言:形>と間違って予測)
            [
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # ので (IGNORE)
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # ご飯
            [
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # を (IGNORE)
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # 食べ (<モダリティ-勧誘>ではなく<モダリティ-命令>、<敬語:丁寧表現>ではなく<敬語:謙譲表現>と間違って予測)
            [
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # ましょう (IGNORE)
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # 。 (IGNORE)
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
        ]
    ],
    dtype=torch.long,
)
base_phrase_features = torch.tensor(
    [
        [
            # お腹
            [
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # が
            [IGNORE_INDEX] * len(BASE_PHRASE_FEATURES),
            # 空いた
            [
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # ので (IGNORE)
            [IGNORE_INDEX] * len(BASE_PHRASE_FEATURES),
            # ご飯
            [
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # を (IGNORE)
            [IGNORE_INDEX] * len(BASE_PHRASE_FEATURES),
            # 食べ
            [
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            # ましょう (IGNORE)
            [IGNORE_INDEX] * len(BASE_PHRASE_FEATURES),
            # 。 (IGNORE)
            [IGNORE_INDEX] * len(BASE_PHRASE_FEATURES),
        ]
    ],
    dtype=torch.long,
)

phrase_analysis_metric = PhraseAnalysisMetric()
phrase_analysis_metric_args = {
    "example_ids": torch.as_tensor([0]),
    "word_feature_predictions": word_feature_predictions,
    "word_features": word_features,
    "base_phrase_feature_predictions": base_phrase_feature_predictions,
    "base_phrase_features": base_phrase_features,
}
phrase_analysis_metric.update(**phrase_analysis_metric_args)
for attr in phrase_analysis_metric_args.keys():
    setattr(
        phrase_analysis_metric,
        attr,
        torch.cat(getattr(phrase_analysis_metric, attr), dim=0),
    )
results = phrase_analysis_metric.compute()


def test_phrase_analysis_metric():
    epsilon = 1e-8

    # word features
    # prec, rec = 5 / 5, 5 / 5
    assert results["基本句-主辞_f1"] == 1.0
    prec, rec = 3 / 5, 3 / 4  # スパンレベル
    f1 = 2 * prec * rec / (prec + rec)
    assert abs(results["基本句-区切_f1"] - f1) < epsilon
    # prec, rec = 4 / 4, 4 / 4  # スパンレベル
    assert results["文節-区切_f1"] == 1.0
    # prec, rec = 2 / 2, 2 / 2
    assert results["用言表記先頭_f1"] == 1.0
    # prec, rec = 1 / 2, 1 / 2
    assert results["用言表記末尾_f1"] == 0.5

    # base phrase features
    prec, rec = 1 / 1, 1 / 2
    f1 = 2 * prec * rec / (prec + rec)
    assert abs(results["用言:動_f1"] - f1) < epsilon
    # prec, rec = 2 / 2, 2 / 2
    assert results["体言_f1"] == 1.0
    # prec, rec = 1 / 1, 1 / 1
    assert results["モダリティ-意志_f1"] == 1.0
    # prec, rec = 0 / 0, 0 / 1
    assert results["モダリティ-勧誘_f1"] == 0.0
    # prec, rec = 2 / 2, 2 / 2
    assert results["節-主辞_f1"] == 1.0
    # prec, rec = 2 / 2, 2 / 2
    assert results["節-区切_f1"] == 1.0
    # prec, rec = 1 / 1, 1 / 1
    assert results["レベル:B+_f1"] == 1.0
    # prec, rec = 1 / 1, 1 / 1
    assert results["レベル:C_f1"] == 1.0
    # prec, rec = 1 / 1, 1 / 1
    assert results["動態述語_f1"] == 1.0
    # prec, rec = 0 / 0, 0 / 1
    assert results["敬語:丁寧表現_f1"] == 0.0
