name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    # https://docs.pypi.org/trusted-publishers/
    environment:
      name: pypi
      url: https://pypi.org/p/kwja
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: false
      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        run: uv publish
