name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          body: |
            [Changelog](https://github.com/ku-nlp/kwja/blob/main/CHANGELOG.md)
          prerelease: false
